package com.nikolaenko.playground.core.ui.attr

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val DarkColorMaterialPalette = darkColorScheme(
//    primary = DarkColors.primary,
//    onPrimary = DarkColors.onPrimary,
//    primaryContainer = DarkColors.primaryContainer,
//    onPrimaryContainer = DarkColors.onPrimaryContainer,
//    secondary = DarkColors.secondary,
//    onSecondary = DarkColors.onSecondary,
//    secondaryContainer = DarkColors.secondaryContainer,
//    onSecondaryContainer = DarkColors.onSecondaryContainer,
//    tertiary = DarkColors.tertiary,
//    onTertiary = DarkColors.onTertiary,
//    tertiaryContainer = DarkColors.tertiaryContainer,
//    onTertiaryContainer = DarkColors.onTertiaryContainer,
//    error = DarkColors.error,
//    errorContainer = DarkColors.errorContainer,
//    onError = DarkColors.onError,
//    onErrorContainer = DarkColors.onErrorContainer,
//    background = DarkColors.background,
//    onBackground = DarkColors.onBackground,
//    surface = DarkColors.surface,
//    onSurface = DarkColors.onSurface,
//    surfaceVariant = DarkColors.surfaceVariant,
//    onSurfaceVariant = DarkColors.onSurfaceVariant,
//    outline = DarkColors.outline,
//    inverseOnSurface = DarkColors.inverseOnSurface,
//    inverseSurface = DarkColors.inverseSurface,
//    inversePrimary = DarkColors.inversePrimary,
//    surfaceTint = DarkColors.surfaceTint,
//    outlineVariant = DarkColors.outlineVariant,
//    scrim = DarkColors.scrim,
)

internal val LightColorMaterialPalette = lightColorScheme(
//    primary = LightColors.primary,
//    onPrimary = LightColors.onPrimary,
//    primaryContainer = LightColors.primaryContainer,
//    onPrimaryContainer = LightColors.onPrimaryContainer,
//    secondary = LightColors.secondary,
//    onSecondary = LightColors.onSecondary,
//    secondaryContainer = LightColors.secondaryContainer,
//    onSecondaryContainer = LightColors.onSecondaryContainer,
//    tertiary = LightColors.tertiary,
//    onTertiary = LightColors.onTertiary,
//    tertiaryContainer = LightColors.tertiaryContainer,
//    onTertiaryContainer = LightColors.onTertiaryContainer,
//    error = LightColors.error,
//    errorContainer = LightColors.errorContainer,
//    onError = LightColors.onError,
//    onErrorContainer = LightColors.onErrorContainer,
//    background = LightColors.background,
//    onBackground = LightColors.onBackground,
//    surface = LightColors.surface,
//    onSurface = LightColors.onSurface,
//    surfaceVariant = LightColors.surfaceVariant,
//    onSurfaceVariant = LightColors.onSurfaceVariant,
//    outline = LightColors.outline,
//    inverseOnSurface = LightColors.inverseOnSurface,
//    inverseSurface = LightColors.inverseSurface,
//    inversePrimary = LightColors.inversePrimary,
//    surfaceTint = LightColors.surfaceTint,
//    outlineVariant = LightColors.outlineVariant,
//    scrim = LightColors.scrim,
)